Initial Conditions
festim-dev/FESTIM pull request #640
Opened 2023-11-14 20:51 UTC by jhdark

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to FESTIM?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

- [ ] Black formatted
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-11-14 20:58 UTC, RemDelaporteMathurin commented on festim/initial_condition.py
> +            if "t" in arguments and "x" not in arguments and "T" not in arguments:
How come "t" can be in the arguments for an initial condition?

2023-11-21 13:46 UTC, RemDelaporteMathurin requested changes
First round of comments

2023-11-21 13:46 UTC, RemDelaporteMathurin commented on festim/initial_condition.py
> +        >>> InitialCondition(volume=my_vol, value=lambda x, t: 1 + x[0] + t, species="H")
According to the docstrings, the `species` argument is of type `festim.Species` not `str`

2023-11-21 13:46 UTC, RemDelaporteMathurin commented on festim/initial_condition.py
> +        self.volume = volume
Maybe it's best to keep this for later but the main question here is: how to apply an initial condition in one subdomain only?

2023-11-21 13:46 UTC, RemDelaporteMathurin commented on festim/hydrogen_transport_problem.py
> +        initial_conditions=[],
This should be documented

2023-11-21 15:28 UTC, jhdark commented on festim/initial_condition.py
> +                raise ValueError("Initial condition cannot be a function of time.")
Can do

2023-12-03 15:18 UTC, RemDelaporteMathurin requested changes

2023-12-03 15:18 UTC, RemDelaporteMathurin commented on festim/hydrogen_transport_problem.py
> +                    if spe == condition.species:
@jhdark can we address this?

It should look something like:

```python
idx = self.species.index(spe)
```

2023-12-03 15:18 UTC, RemDelaporteMathurin commented on test/test_h_transport_problem.py
> +    assert np.isclose(my_model.u_n.sub(1).x.array[-1], expected_value_2)
It isn't clear to me why we have [-2] and [-1] here

2023-12-03 15:18 UTC, RemDelaporteMathurin commented on festim/initial_condition.py
> +                kwargs["t"] = t
@jhdark can we address this?

2023-12-04 10:24 UTC, jhdark commented on festim/initial_condition.py
> +                kwargs["t"] = t
As in we should have `kwargs["t"] = 0`?

2023-12-05 10:17 UTC, RemDelaporteMathurin commented on festim/initial_condition.py
> +                kwargs["t"] = t
yes

2023-12-06 10:55 UTC, RemDelaporteMathurin commented
I don't see where it uses `InitialCondition.subdomain` are you sure that initial values in subdomains is implemented?

2023-12-07 13:29 UTC, RemDelaporteMathurin commented on test/test_h_transport_problem.py
> +    assert np.isclose(my_model.u_n.x.array[-1], expected_value_2)
Could we add just a comment here explaining the [-2] [-1] thing?

2023-12-11 13:58 UTC, merged