Update README.md
festim-dev/FESTIM pull request #651
Opened 2023-11-26 22:33 UTC by tadash10

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to FESTIM?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

- [ ] Black formatted
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-11-26 23:45 UTC, RemDelaporteMathurin requested changes
Hi @tadash10 and welcome 🎉 😄 

Thanks for your PR! This will be needed for newcomers!

Here are a few suggestions:
- instead of describing the purpose of the PR in a comment, you can do it in the body of the PR under "Proposed changes".
- instead of copy pasting the issue, you can refer to it using its id like this #650 
- we should also add the discourse forum to the documentation page, in the [Where can I find help](https://festim.readthedocs.io/en/latest/userguide/beginners_guide.html) section. To do so, you can modify [this file](https://github.com/festim-dev/FESTIM/blob/main/docs/source/userguide/beginners_guide.rst)

2023-11-27 15:08 UTC, tadash10 commented
https://github.com/festim-dev/FESTIM/issues/650 update .Thanks a lot for the quick review and positive feedback!

2023-11-27 15:57 UTC, RemDelaporteMathurin commented on docs/source/userguide/beginners_guide.rst
> +Join the FESTIM community on our https://festim.discourse.group. Engage in discussions, ask questions, and connect with other users. This is a collaborative space where you can share your experiences
```suggestion
----------------------
Where can I find help?
----------------------

If you're having an issue, the best way to find help is to join the `FESTIM discourse <https://festim.discourse.group>`. Engage in discussions, ask questions, and connect with other users. This is a collaborative space where you can share your experiences and seek assistance.
```

2023-11-27 16:11 UTC, RemDelaporteMathurin commented on docs/source/userguide/beginners_guide.rst
> +If you're having an issue, the best way to find help is to join the `FESTIM discourse <https://festim.discourse.group>`. Engage in discussions, ask questions, and connect with other users. This is a
```suggestion
If you're having an issue, the best way to find help is to join the `FESTIM discourse <https://festim.discourse.group>`_. Engage in discussions, ask questions, and connect with other users. This is a collaborative space where you can share your experiences and seek assistance.
```

2023-11-27 16:18 UTC, RemDelaporteMathurin approved these changes

2023-11-27 16:20 UTC, merged