Fix bug with calculations on small timescales
festim-dev/FESTIM pull request #682
Opened 2024-01-16 21:04 UTC by KulaginVladimir

## Proposed changes

When performing simulations on small timescales (e.g., `final_time=1e-7`), some bugs appear due to the use of `np.isclose` with the default parameters (atol, rtol). For example (see below), computation stops without reaching the final time. As @RemDelaporteMathurin suggested, the current PR attempts to fix the bug by setting `atol=0` in `np.isclose`. 

## Types of changes

What types of changes does your code introduce to FESTIM?

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

- [x] Black formatted
- [x] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments
MWE:
```python
import festim as F
import numpy as np

my_model = F.Simulation(log_level = 40)

my_model.mesh = F.MeshFromVertices(np.linspace(0, 1, 10))

my_model.materials = F.Material(
    id=1,
    D_0=1,
    E_D=0.1,
)

my_model.T = F.Temperature(1000)

my_model.settings = F.Settings(
    absolute_tolerance=1e-10,
    relative_tolerance=1e-10,
    final_time=1e-7,
)

my_model.dt = F.Stepsize(
    initial_value=1e-10,
)

my_model.initialise()
my_model.run()
``` 
Stops at 90%:
```
Defining initial values
Defining variational problem
Defining source terms
Defining boundary conditions
Time stepping...
90.0 %        9.0e-08 s    Ellapsed time so far: 3.2 s
```

2024-01-16 21:09 UTC, RemDelaporteMathurin commented
Very nice MWE @KulaginVladimir , would you mind making use of it in a test that catches the bug?

I think you can do something like:


```python
def test_small_timesteps_final_time_bug():
    """Some description"""
    my_model = F.Simulation(log_level = 40)
    
    my_model.mesh = F.MeshFromVertices(np.linspace(0, 1, 10))
    
    my_model.materials = F.Material(
        id=1,
        D_0=1,
        E_D=0.1,
    )
    
    my_model.T = F.Temperature(1000)
    
    my_model.settings = F.Settings(
        absolute_tolerance=1e-10,
        relative_tolerance=1e-10,
        final_time=1e-7,
    )
    
    my_model.dt = F.Stepsize(
        initial_value=1e-10,
    )
    
    my_model.initialise()
    my_model.run()

    assert np.isclose(my_model.t, my_model.settings.final_time, atol=0.0)

2024-01-17 13:01 UTC, RemDelaporteMathurin requested changes
Hi @KulaginVladimir just a small comment on my side, Thanks for this fix! 🚀

2024-01-17 13:29 UTC, KulaginVladimir commented on test/system/test_misc.py
>      )
Nice idea

2024-01-17 18:36 UTC, RemDelaporteMathurin approved these changes
Looks good to me thanks @KulaginVladimir

2024-01-18 13:48 UTC, merged