Soret coefficient as a function of temperature
festim-dev/FESTIM pull request #690
Opened 2024-01-26 17:08 UTC by KulaginVladimir

This PR makes it possible to set the Soret coefficient as a function of temperature, according to #458. Following the discussion, the parameter is renamed to `Q` and expressed in eV. Most of the changes are made based on #468.

Basic usage:
```python
from FESTIM import Material

my_mat = Material(id=1, D_0=1, E_D=0, Q=lambda T: 2 + 5 * T)
# or
my_mat = Material(id=1, D_0=1, E_D=0, Q=10)

``` 
## Types of changes

What types of changes does your code introduce to FESTIM?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [x] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

- [x] Black formatted
- [x] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2024-01-26 19:14 UTC, jhdark commented
@mougenj Its finally coming!

2024-01-26 19:26 UTC, RemDelaporteMathurin requested changes
Thanks for this PR @KulaginVladimir , just a small comment on the docstrings, we could add an example of using a `lambda` function.

Also, do we have an MMS test for the soret effect? I don't know if we tested it thoroughly or not. Can be done in a separate PR if we don't

2024-01-26 20:01 UTC, KulaginVladimir commented on festim/materials/material.py
> +        Q (float or callable, optional): heat of transport (eV). Can
Well, `thermal_cond`, `heat_capacity`, `rho` also can be temperature-dependent. Thus, wouldn't it be beneficial to provide a more general example via [`Example ::`](https://github.com/festim-dev/FESTIM/blob/2ae06c1357194c105d6e4d415c88d105a11258fd/festim/sources/source_implantation_flux.py#L22-L29), e.g.:
```python
my_mat = Material(
    id = 1,
    D_0 = 2e-7,
    E_d = 0.2,
    thermal_cond = lambda T: 3 * T + 2,
    heat_capacity = lambda T: 4 * T + 8,
    rho = lambda T: 7 * T + 5,
    Q = lambda T: -0.5 * T**2
)
``` 

Concerning MMS test for Soret, this is what is currently done in tests: https://github.com/festim-dev/FESTIM/blob/2ae06c1357194c105d6e4d415c88d105a11258fd/test/system/test_system.py#L466-L555

Aside from that, there is a minor drop in the code coverage. Is it OK?

2024-01-26 20:27 UTC, RemDelaporteMathurin commented on festim/materials/material.py
> +        Q (float or callable, optional): heat of transport (eV). Can
> wouldn't it be beneficial to provide a more general example

Yes

> Aside from that, there is a minor drop in the code coverage. Is it OK?

This is due to the removal of some code. This often happens during refactoring. What I'm looking at first is the patch coverage: how many lines that were modified are covered. And the patch coverage is 100% so we're good.

2024-01-26 20:33 UTC, RemDelaporteMathurin commented on festim/materials/material.py
> +        Q (float or callable, optional): heat of transport (eV). Can
Yes @KulaginVladimir you are right this is the MMS test we have for the Soret effect.

2024-01-27 00:55 UTC, RemDelaporteMathurin approved these changes
Thanks @KulaginVladimir 🚀  I'll leave this open to leave others the time to make some comments if needed.

2024-01-29 14:36 UTC, merged