Reset derived quantity objects data and t at the beginning of a simulation
festim-dev/FESTIM pull request #733
Opened 2024-04-02 22:49 UTC by Allentro

## Proposed changes

I have implemented a fix to reset export.t and export.data at the beginning of a simulation, accompanied by a respective test. This PR resolves #728 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [x] New tests

## Checklist

- [x] Black formatted
- [x] Unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2024-04-03 13:39 UTC, RemDelaporteMathurin requested changes
Initial round of comments, the fix obviously works fine, but it's not the right place for it.

2024-04-03 13:39 UTC, RemDelaporteMathurin commented on festim/hydrogen_transport_problem.py
> +            export.data = []
Doing it here is not the right place.
This iterates through all the exports, which can be derived quantities, but also VTXExport or XDMFExport etc.

Instead, we could do it in `write()`, making use of the `self._is_first_time_export` attribute. For example here:

https://github.com/festim-dev/FESTIM/blob/f08f0b5c83d11b511a129316d040b61d0bf4f3b1/festim/exports/surface_quantity.py#L75-L76

2024-04-03 13:39 UTC, RemDelaporteMathurin commented on festim/hydrogen_transport_problem.py
> +            export.data = []
Alternatively we could do it here, but with an additional type check to only do this for derived quantities.

2024-04-03 13:39 UTC, RemDelaporteMathurin commented on test/test_h_transport_problem.py
> +    )
Can you parametrise this test to also check for other derived quantities (eg. TotalVolume)

2024-05-17 14:59 UTC, RemDelaporteMathurin commented
Hey @Allentro what is the status of this?

2024-05-29 11:28 UTC, Allentro commented
> Hey @Allentro what is the status of this?

Hi Remi, sorry this has slipped my list. I'll get this complete tomorrow!

2024-08-18 21:07 UTC, Allentro commented
> Hi @Allentro! Do you want someone else to pick up this PR?

Hi Remi, 

This slipped my inbox.. I was just scrolling through my mentions and saw this. I'm happy to work on this tomorrow evening. Sorry for the delay on this.

2024-11-04 19:02 UTC, RemDelaporteMathurin approved these changes

2024-11-04 19:02 UTC, merged