Update the information in the XDMF section
festim-dev/FESTIM pull request #801
Opened 2024-07-06 12:25 UTC by XinShen-CHN

## Proposed changes

Some updated information in the XDMF section of the documentation. #799

## Types of changes

What types of changes does your code introduce to FESTIM?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ x ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

- [ ] Black formatted
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2024-07-06 12:55 UTC, RemDelaporteMathurin commented
Thanks for this contribution @XinShen-CHN!

Just letting you know that you can visualise the compiled documentation [here](https://festim--801.org.readthedocs.build/en/801/).

you can also compile the documentation locally. To do so follow the Documentation guide in the Developer’s guide.

2024-07-06 13:00 UTC, RemDelaporteMathurin requested changes
Thanks @XinShen-CHN for that first contribution 🎉 

Here are a few remarks that would need to be addressed before merging.

2024-07-07 06:48 UTC, XinShen-CHN commented on docs/source/userguide/export_post_processing.rst
> +- Find out more information on `Paraview tutorials <https://www.paraview.org/tutorials/>`_
Thank you very much!

Sure, I'll modify the documentation and add the new tip.

2024-07-07 09:58 UTC, RemDelaporteMathurin approved these changes
Looks good to me! I'll leave this open a little while longer to give others a chance to make some comments and then we can merge this PR.

2024-07-08 07:53 UTC, merged