#824
festim-dev/FESTIM pull request #862
Opened 2024-08-02 11:45 UTC by XinShen-CHN

## Proposed changes

Store user logos locally to avoid missing markers in map.

## Types of changes

What types of changes does your code introduce to FESTIM?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [x] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

- [ ] Black formatted
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-08-02 11:56 UTC, RemDelaporteMathurin requested changes
Thanks @XinShen-CHN 

Could you add all the logos in a subdirectory within images please?

`images/user_logos/`

Also have a few requests about the code.

2024-08-02 11:56 UTC, RemDelaporteMathurin commented on docs/source/map.py
You can rename the `url` variable to `path` here.

2024-08-02 11:56 UTC, RemDelaporteMathurin commented on docs/source/map.py
In this file you can also now remove the function `get_image_dimensions_from_url` since we don't use it anymore.

2024-08-02 11:56 UTC, RemDelaporteMathurin commented on docs/source/images/ENEA.png
Please use this logo for ENEA 
https://mongoos.eurogoos.eu/wp-content/uploads/ENEA.jpg

2024-08-02 11:56 UTC, RemDelaporteMathurin commented on docs/source/images/digiLab_UK.png
Can you use this logo please?
https://media.licdn.com/dms/image/D560BAQFiF6vq2h-9pw/company-logo_200_200/0/1697037256438/digilab_solutions_ltd_logo?e=2147483647&v=beta&t=EOuAtbXf7B0ZBvDPfEYf2H6Pw9au6-FYUN8XNKBNS4E

2024-08-02 11:56 UTC, RemDelaporteMathurin commented on docs/source/images/MIT_Cambridge_MA_USA.png
can you use this logo for MIT please

https://brand.mit.edu/sites/default/files/styles/image_text_2x/public/2023-08/MIT-lockup-3line-red.png?itok=MJP9Djff

2024-08-02 11:56 UTC, RemDelaporteMathurin commented on docs/source/images/University_Wisconsin_Madison_USA.png
Can you use this logo for UW

https://brand.wisc.edu/content/uploads/2023/09/vert-w-crest-logo-web-digital-color.png

2024-08-02 13:17 UTC, RemDelaporteMathurin requested changes
Thanks Xin! Could you please format your code with black?

Install black:
```
pip install black
```

Format your script:
```
black map.py
```

2024-08-02 13:20 UTC, KulaginVladimir commented
Hi @XinShen-CHN, could you please add this logo for MEPhI?
![С конём и дескриптором](https://github.com/user-attachments/assets/75c0c9a9-93e5-4e75-ad2b-fa954249bf19)

The source file can be downloaded with this link: https://mephi.ru/content/public/uploads/files/angl.zip
or this: https://logowik.com/national-research-nuclear-university-mephi-logo-vector-svg-pdf-ai-eps-cdr-free-download-16416.html

2024-08-04 10:39 UTC, XinShen-CHN commented
> Hi @XinShen-CHN, could you please add this logo for MEPhI? ![С конём и дескриптором](https://private-user-images.githubusercontent.com/59147151/354607319-75c0c9a9-93e5-4e75-ad2b-fa954249bf19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NjgyNjQsIm5iZiI6MTcyMjc2Nzk2NCwicGF0aCI6Ii81OTE0NzE1MS8zNTQ2MDczMTktNzVjMGM5YTktOTNlNS00ZTc1LWFkMmItZmE5NTQyNDliZjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDEwMzkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmOTliODUwMGU5NjI1MmZlNTMyYzVhNjYxNjNhMGNhNmQ2OTljNmE3MTRmYmQ1ZjU1YmFiMWY0NTMwNGIyZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6at8iRE_i7D968kcZVKw4WqH-PDkLmC6mW9TuwkxOh0)
> 
> The source file can be downloaded with this link: https://mephi.ru/content/public/uploads/files/angl.zip or this: https://logowik.com/national-research-nuclear-university-mephi-logo-vector-svg-pdf-ai-eps-cdr-free-download-16416.html

Sure.

2024-08-04 10:42 UTC, XinShen-CHN commented
> Thanks Xin! Could you please format your code with black?
> 
> Install black:
> 
> ```
> pip install black
> ```
> 
> Format your script:
> 
> ```
> black map.py
> ```

I'd love to, but I'm stuck with formatting the code with blank.

2024-08-04 12:50 UTC, RemDelaporteMathurin commented
> I'd love to, but I'm stuck with formatting the code with black.

I can help. What is your issue?

2024-08-05 02:53 UTC, XinShen-CHN commented
> > I'd love to, but I'm stuck with formatting the code with black.
> 
> I can help. What is your issue?

Thank you! No worries. I think I've settled it.

2024-08-05 07:57 UTC, XinShen-CHN commented
New problem. It has been loading for hours after I clicked the commit.
![image](https://github.com/user-attachments/assets/61c849c4-85fd-46ff-b9e8-50787aa8f526)

2024-08-05 08:07 UTC, RemDelaporteMathurin commented
> New problem. It has been loading for hours after I clicked the commit. ![image](https://private-user-

Have you entered a commit message before clicking "Commit"?

2024-08-05 10:21 UTC, XinShen-CHN commented
> > New problem. It has been loading for hours after I clicked the commit. ![image](https://private-user-
> 
> Have you entered a commit message before clicking "Commit"?

Thanks! I'm not familar with the desktop version of VS Code for using it first time.

2024-08-05 10:39 UTC, RemDelaporteMathurin approved these changes
Thanks @XinShen-CHN for this improvement! 🚀🚀

General feedback: you should try to have commits message that are specific to the changes in each commit. Here all the commits have the same message. A specific message would be for example "formatted code with black" or "moved files to subdirectory", "changed variable names" etc.

2024-08-05 11:04 UTC, XinShen-CHN commented
> Thanks @XinShen-CHN for this improvement! 🚀🚀
> 
> General feedback: you should try to have commits message that are specific to the changes in each commit. Here all the commits have the same message. A specific message would be for example "formatted code with black" or "moved files to subdirectory", "changed variable names" etc.

Got it!

2024-08-05 11:09 UTC, RemDelaporteMathurin commented
@XinShen-CHN I just pushed to your branch to add the changes added by @iamryo on #853

2024-08-05 11:15 UTC, merged