Documentation: how to run FESTIM in parallel #856
festim-dev/FESTIM pull request #871
Opened 2024-08-08 14:12 UTC by XinShen-CHN

## Proposed changes

Documentation: how to run FESTIM in parallel #856.

## Types of changes

What types of changes does your code introduce to FESTIM?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [x] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

- [ ] Black formatted
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-08-09 10:30 UTC, RemDelaporteMathurin requested changes
Thanks @XinShen-CHN for adding this!

I see that the documentation test is failing. See my comment below.

@KulaginVladimir do you think this should be at the bottom of this page in "Your first FESTIM script"?

2024-08-09 10:30 UTC, RemDelaporteMathurin commented on docs/source/userguide/beginners_guide.rst
> +.. testcode::
```suggestion
.. code::
```

If you use ``testcode`` this code block will be tested as if it was a python code block. This obviously won't work and this is why the documentation test is failing. 
Simply replace this by a normal code block.

2024-08-09 10:52 UTC, KulaginVladimir commented
@RemDelaporteMathurin, I don't. Since parallel computing doesn't always result in faster computation, I wouldn't put it in the "your first FESTIM script". 

Personally, I'd make a separate page that could be filled with some additional info/hints/warnings later. 

We could also make a demo to show when parallel computing might speed up a simulation.

2024-08-09 12:22 UTC, XinShen-CHN commented
> Thanks @XinShen-CHN for adding this!
> 
> I see that the documentation test is failing. See my comment below.

Thank you Remi!

2024-08-09 17:57 UTC, RemDelaporteMathurin commented
> Personally, I'd make a separate page that could be filled with some additional info/hints/warnings later.

@XinShen-CHN could you make a new User Guide page "Running in parallel" and move the content there instead?

2024-08-12 08:44 UTC, RemDelaporteMathurin requested changes
Xin, you need to:
- provide the correct extension for the new file (.rst). Also, avoid blank spaces and uppercase letters in filenames. `running_in_parallel.rst` would be an appropriate filename.
- add this new file in `docs/source/userguide/index.rst` if you want it to be counted.

I advise you to try and build the documentation locally on your computer to be able to inspect your changes. Here you will see that these lines don't appear anywhere in the [automatically-built documentation](https://festim--871.org.readthedocs.build/en/871/userguide/index.html).

2024-08-22 02:58 UTC, XinShen-CHN commented
> Xin, you need to:
> 
> * provide the correct extension for the new file (.rst). Also, avoid blank spaces and uppercase letters in filenames. `running_in_parallel.rst` would be an appropriate filename.
> * add this new file in `docs/source/userguide/index.rst` if you want it to be counted.
> 
> I advise you to try and build the documentation locally on your computer to be able to inspect your changes. Here you will see that these lines don't appear anywhere in the [automatically-built documentation](https://festim--871.org.readthedocs.build/en/871/userguide/index.html).

I see. I'll try to fix it.

Sorry for the delays. I was on a vacation.

2024-08-30 20:30 UTC, RemDelaporteMathurin commented
Hi @XinShen-CHN do you need assistance on this?

2024-09-03 08:32 UTC, XinShen-CHN commented
> Hi @XinShen-CHN do you need assistance on this?

Yes, I failed to build the documentation locally.

2024-09-09 12:26 UTC, RemDelaporteMathurin reviewed
Hi @XinShen-CHN thanks for these changes. I can assist you in building the docs locally. In the meantime, here's a final suggestion (I'll commit): we need to have a title (with # ) in this page to avoid this:

<img width="1046" alt="image" src="https://github.com/user-attachments/assets/19a2cfc8-4a23-4897-916d-2da862d9af7f">

2024-09-09 12:26 UTC, RemDelaporteMathurin commented on docs/source/userguide/running_in_parallel.rst
> +FESTIM can be run in parallel on N cores using the command:
```suggestion
# Running in parallel

FESTIM can be run in parallel on N cores using the command: 
```

2024-09-09 15:41 UTC, RemDelaporteMathurin commented on docs/source/userguide/running_in_parallel.rst
> +# Running in parallel
```suggestion
============
Running in parallel
============
```

2024-09-09 20:31 UTC, RemDelaporteMathurin commented on docs/source/userguide/running_in_parallel.rst
> +    mpirun -np N python3 your_FESTIM_script.py.
```suggestion
    mpirun -np N python3 your_FESTIM_script.py
```

2024-09-12 17:17 UTC, RemDelaporteMathurin approved these changes

2024-09-12 17:17 UTC, merged

2024-09-13 07:33 UTC, XinShen-CHN commented
> Hi @XinShen-CHN thanks for these changes. I can assist you in building the docs locally. In the meantime, here's a final suggestion (I'll commit): we need to have a title (with # ) in this page to avoid this:
> 
> <img alt="image" width="1046" src="https://private-user-images.githubusercontent.com/40028739/365648690-19a2cfc8-4a23-4897-916d-2da862d9af7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTMwMzYsIm5iZiI6MTcyNjIxMjczNiwicGF0aCI6Ii80MDAyODczOS8zNjU2NDg2OTAtMTlhMmNmYzgtNGEyMy00ODk3LTkxNmQtMmRhODYyZDlhZjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA3MzIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMWJhMTI0MzdkM2JiZjNjYjQ2MmE0MDhmNDA2MDM3MzAyOTEwOTY1NTY4ODJkYTY5MjMwMTlkZDQ1ZmQzMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Ns5NDrO0wCQypIQUJKMlsbr9ijjnMmCwBY-tpOwiys">

Remi, thank you so much!